#!/bin/bash

#Color Codes
RED='\e[1;31m'
GREEN='\e[1;32m'
YELLOW='\e[1;33m'
BLUE='\e[1;34m'
CYNE='\e[1;36m'
RESET='\e[1;0m'

# Input Check
TARGET=$1

if [ -z "$TARGET" ]; then
    echo -e "${RED}[!] Error: No domain/IP provided! ${RESET}"
    echo -e "${YELLOW}Usage: $0 <domain-name>${RESET}"
    echo -e "Example: $0 domain.com"
    exit 1
fi

# Tools check
TOOLS=("whois" "whatweb" "dig" "waf00f")

for tool in "${TOOLS}"; do
  if ! command -v $tool &> /dev/null; then
    echo -e "${RED}[!]Error: '$tool' in not installed. Please install it first"
    exit 1
  fi
done

echo -e "${GREEN}[*] Starting Reconnaissance on: ${TARGET}${RESET}\n"

# Executing Commands
echo -e "${GREEN}[+]Whois lookup${RESET}"
whois ${TARGET} 2>/dev/null | head -22 || echo -e "${RED}[!] Whois lookup failed"

echo -e "\n${YELLOW}[+] Whatweb Scanning...${RESET}"
whatweb ${TARGET} 2>/dev/null | grep -E "200 OK|302 Found" || echo -e "${RED}[!] 200 OK response not found${RESET}"

echo -e "\n${GREEN}[+] DNS information ${RESET}"
dig ${TARGET} 2>/dev/null | tail -n+13 | head -3 || echo -e "${RED}[!] DNS info not found ${RESET}"

echo -e "\n${CYNE}[+] NS Query ${RESET}"
dig ${TARGET} ns 2>/dev/null | tail -n+13 | head -3 || echo -e "${RED}[!] Nameserver not found ${RESET}"

echo -e "\n${BLUE}[+] WA Firewall Scaning...${RESET}"
wafw00f ${TARGET} 2>/dev/null | tail -4 || echo -e "${RED}[!] Firewall info not found ${RESET}"

echo -e "\n${GREEN}[*] Recon Scan Completed successfully! ${RESET}"
